
ktor:
  deployment:
    port: 9000
    host: 0.0.0.0
  application:
    modules:
      - org.burgas.MainKt.modules

postgres:
  url: '$POSTGRES_URL:jdbc:postgresql://localhost:5000/portfolio-case-db'
  user: '$POSTGRES_USER:postgres'
  password: '$POSTGRES_PASSWORD:postgres'

api:
  ktor-server:
    url: '$KTOR_SERVER_URL:http://localhost:9000'

jwt:
  secret: '1a091b7f-21db-4ebe-8cec-d55b3836c7fc'

cookie:
  secret: '1u4i5ot06o4ir85n5m3m6970vjf3k58h'