


### Security Requests



###
POST /api/v1/security/login
Host: localhost:9000
Content-Type: application/json

{
    "email": "burgasvv@gmail.com",
    "password": "burgasvv"
}

###
POST /api/v1/security/logout
Host: localhost:9000



### Identity Requests



###
GET /api/v1/identities
Host: localhost:9000

###
GET /api/v1/identities/by-id?identityId=85197047-0962-4848-b46d-8c064879fe0b
Host: localhost:9000

###
POST /api/v1/identities/create
Host: localhost:9000
Content-Type: application/json

{
    "email": "zagor@gmail.com",
    "password": "zagor",
    "phone": "+79456321587",
    "firstname": "Загорулько",
    "lastname": "Борис",
    "patronymic": "Юрьевич"
}

###
PUT /api/v1/identities/update
Host: localhost:9000
Content-Type: application/json

{
    "id": "4530f5f3-a237-4353-9e1f-25bcbccfdc88",
    "telegram": "@zagor",
    "whatsapp": "@zagorulko",
    "max": "@zagor-boris",
    "about": "Личная информация профиля Загорулько Бориса Юрьевича"
}

###
PUT /api/v1/identities/change-status
Host: localhost:9000
Content-Type: application/json

{
    "id": "1cd14eaa-518d-4cb6-ac0e-4326d36658e9",
    "status": true
}

###
PUT /api/v1/identities/change-password
Host: localhost:9000
Content-Type: application/json

{
    "id": "85197047-0962-4848-b46d-8c064879fe0b",
    "password": "burgasvv"
}

###
POST /api/v1/identities/delete?identityId=d2577048-5447-49d3-b3d4-242365788571
Host: localhost:9000



### Profession Requests



###
GET /api/v1/professions
Host: localhost:9000

###
GET /api/v1/professions/by-id?professionId=42522c7f-3d7f-4237-a287-d84a9fc5e99c
Host: localhost:9000

###
POST /api/v1/professions/create
Host: localhost:9000
Content-Type: application/json

{
    "name": "Java разработчик",
    "description": "IT-специалист, который создает, тестирует и поддерживает программное обеспечение на языке программирования Java."
}

###
PUT /api/v1/professions/update
Host: localhost:9000
Content-Type: application/json

{
    "id": "42522c7f-3d7f-4237-a287-d84a9fc5e99c",
    "name": "Java разработчик/developer"
}

###
DELETE /api/v1/professions/delete?professionId=42522c7f-3d7f-4237-a287-d84a9fc5e99c
Host: localhost:9000



### Portfolio Requests



###
GET /api/v1/portfolios
Host: localhost:9000

###
GET /api/v1/portfolios/by-id?portfolioId=860b79cf-df62-4e83-af56-a87906be68f2
Host: localhost:9000

###
POST /api/v1/portfolios/create
Host: localhost:9000
Content-Type: application/json

{
    "professionId": "1d86c554-7c86-4f62-988c-882377ce6f67",
    "identityId": "85197047-0962-4848-b46d-8c064879fe0b"
}

###
PUT /api/v1/portfolios/update
Host: localhost:9000
Content-Type: application/json

{
    "id": "860b79cf-df62-4e83-af56-a87906be68f2",
    "description": "Эффектное описание профиля Kotlin-разработчика в портфолио должно включать краткое сильное «био»."
}